/**
 * KPI Calculator for Ujamaa Monitor
 * 
 * Transforms raw contract data into human-readable KPIs
 */

import { formatEther, formatBasisPoints } from './rpc';
import { KPI_THRESHOLDS } from '../../config/monitor';

// KPI status types
export type KpiStatus = 'green' | 'amber' | 'red' | 'neutral';

// Formatted KPI value
export interface FormattedKpi<T = number | string> {
  value: T;
  formattedValue: string;
  status: KpiStatus;
  change?: number; // Percentage change
  changeFormatted?: string;
  label: string;
  tooltip: string;
}

// Helper to determine KPI status based on thresholds
const getStatus = (
  value: number,
  thresholds: { green: number; amber: number },
  inverse: boolean = false
): KpiStatus => {
  if (inverse) {
    // Lower is better (e.g., default rate)
    if (value <= thresholds.green) return 'green';
    if (value <= thresholds.amber) return 'amber';
    return 'red';
  } else {
    // Higher is better or range-based
    if (value <= thresholds.green) return 'green';
    if (value <= thresholds.amber) return 'amber';
    return 'red';
  }
};

// Helper to determine range-based status
const getRangeStatus = (
  value: number,
  thresholds: {
    green: { min: number; max: number };
    amber: { min: number; max: number };
  }
): KpiStatus => {
  if (value >= thresholds.green.min && value <= thresholds.green.max) return 'green';
  if (value >= thresholds.amber.min && value <= thresholds.amber.max) return 'amber';
  return 'red';
};

// Format large numbers with K/M/B suffixes
export const formatNumber = (num: number): string => {
  if (num >= 1_000_000_000) {
    return (num / 1_000_000_000).toFixed(2) + 'B';
  }
  if (num >= 1_000_000) {
    return (num / 1_000_000).toFixed(2) + 'M';
  }
  if (num >= 1_000) {
    return (num / 1_000).toFixed(1) + 'K';
  }
  return num.toFixed(2);
};

// Format currency (Euros)
export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('en-IE', {
    style: 'currency',
    currency: 'EUR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

// Format percentage
export const formatPercentage = (value: number, decimals: number = 2): string => {
  return `${value.toFixed(decimals)}%`;
};

// Format NAV per share (special format for token value)
export const formatNavPerShare = (navWei: bigint): FormattedKpi<number> => {
  const nav = formatEther(navWei);
  return {
    value: nav,
    formattedValue: `€${nav.toFixed(4)}`,
    status: 'neutral', // NAV itself doesn't have a status
    label: 'NAV per Share',
    tooltip: 'Net Asset Value per uLP token. Like a stock price, but updates based on pool earnings.',
  };
};

// Format TVL (Total Value Locked)
export const formatTvl = (tvlWei: bigint): FormattedKpi<string> => {
  const tvl = formatEther(tvlWei);
  return {
    value: formatCurrency(tvl),
    formattedValue: formatCurrency(tvl),
    status: 'green', // More TVL is always good
    label: 'Total Value Locked',
    tooltip: 'Total value of assets deposited in the liquidity pool.',
  };
};

// Format yield accrued
export const formatYieldAccrued = (yieldWei: bigint, changePercent?: number): FormattedKpi<string> => {
  const yieldAmount = formatEther(yieldWei);
  const formatted = formatCurrency(yieldAmount);
  
  return {
    value: formatted,
    formattedValue: `+${formatted}`,
    status: 'green', // Yield is always positive
    change: changePercent,
    changeFormatted: changePercent ? `${changePercent > 0 ? '+' : ''}${changePercent.toFixed(1)}%` : undefined,
    label: 'Yield Accrued (24h)',
    tooltip: 'Total yield generated by the pool in the last 24 hours.',
  };
};

// Format default rate
export const formatDefaultRate = (rateBps: bigint): FormattedKpi<number> => {
  const rate = formatBasisPoints(rateBps);
  const status = getStatus(rate, KPI_THRESHOLDS.defaultRate, true); // Inverse: lower is better
  
  return {
    value: rate,
    formattedValue: formatPercentage(rate, 2),
    status,
    label: 'Default Rate',
    tooltip: 'Percentage of financings that have defaulted. Lower is better.',
  };
};

// Format utilization rate
export const formatUtilizationRate = (rateBps: bigint): FormattedKpi<number> => {
  const rate = formatBasisPoints(rateBps);
  const status = getRangeStatus(rate, KPI_THRESHOLDS.poolUtilization);
  
  return {
    value: rate,
    formattedValue: formatPercentage(rate, 1),
    status,
    label: 'Pool Utilization',
    tooltip: 'Percentage of pool funds currently deployed. 80-95% is optimal.',
  };
};

// Format token supply
export const formatTokenSupply = (supplyWei: bigint, symbol: string): FormattedKpi<string> => {
  const supply = formatEther(supplyWei);
  
  return {
    value: supply,
    formattedValue: formatNumber(supply) + ' ' + symbol,
    status: 'neutral',
    label: 'Total Supply',
    tooltip: `Total number of ${symbol} tokens in circulation.`,
  };
};

// Format holder count
export const formatHolderCount = (count: number): FormattedKpi<number> => {
  return {
    value: count,
    formattedValue: count.toLocaleString(),
    status: 'green', // More holders is good
    label: 'Total Holders',
    tooltip: 'Number of unique wallets holding uLP tokens.',
  };
};

// Format active financings
export const formatActiveFinancings = (count: number): FormattedKpi<number> => {
  return {
    value: count,
    formattedValue: count.toString(),
    status: 'neutral',
    label: 'Active Financings',
    tooltip: 'Number of active financing operations (loans to industrials).',
  };
};

// Format guarantee/NFT count
export const formatGuaranteeCount = (
  total: number,
  active: number,
  redeemed: number
): FormattedKpi<string> => {
  return {
    value: `${active}/${total}`,
    formattedValue: `${active} active / ${redeemed} redeemed`,
    status: 'neutral',
    label: 'Guarantee Tokens (UJG)',
    tooltip: 'Collateral NFTs backing the pool. Active = held as collateral, Redeemed = returned after repayment.',
  };
};

// Format registered industrials
export const formatIndustrials = (registered: number, pending: number): FormattedKpi<string> => {
  return {
    value: registered,
    formattedValue: `${registered} registered (${pending} pending)`,
    status: pending > 5 ? 'amber' : 'green',
    label: 'Registered Industrials',
    tooltip: 'Companies approved to receive financing. Pending = awaiting approval.',
  };
};

// Calculate NAV change percentage
export const calculateNavChange = (currentNav: number, previousNav: number): number => {
  if (previousNav === 0) return 0;
  return ((currentNav - previousNav) / previousNav) * 100;
};

// Calculate composite Pool Health Score (0-100)
export const calculatePoolHealthScore = (kpis: {
  defaultRate: number;
  utilizationRate: number;
  navChange: number;
  liquidityRatio: number;
}): number => {
  const weights = {
    defaultRate: 0.3,
    utilizationRate: 0.25,
    navChange: 0.25,
    liquidityRatio: 0.2,
  };

  // Score each metric (0-100)
  const scores = {
    defaultRate: Math.max(0, 100 - (kpis.defaultRate * 50)), // 0% = 100, 2% = 0
    utilizationRate: kpis.utilizationRate >= 80 && kpis.utilizationRate <= 95
      ? 100
      : kpis.utilizationRate >= 70 && kpis.utilizationRate <= 100
      ? 60
      : 30,
    navChange: Math.max(0, 100 - (Math.abs(kpis.navChange) * 20)), // 0% change = 100
    liquidityRatio: Math.min(100, kpis.liquidityRatio * 10), // 10% = 100
  };

  // Weighted average
  const healthScore =
    scores.defaultRate * weights.defaultRate +
    scores.utilizationRate * weights.utilizationRate +
    scores.navChange * weights.navChange +
    scores.liquidityRatio * weights.liquidityRatio;

  return Math.round(healthScore);
};

// Get health score color
export const getHealthScoreColor = (score: number): string => {
  if (score >= 80) return 'text-green-500';
  if (score >= 60) return 'text-yellow-500';
  if (score >= 40) return 'text-orange-500';
  return 'text-red-500';
};

// Get health score label
export const getHealthScoreLabel = (score: number): string => {
  if (score >= 80) return 'Excellent';
  if (score >= 60) return 'Good';
  if (score >= 40) return 'Fair';
  return 'Needs Attention';
};
